### ISSUE TITLE
Мой первый issues

### ISSUE THREAD

**Issue by UMSF-K13-3-Sahan** [UMSF-K13-3-Sahan/UMSF-K13-3-Sahan-mainproject#1]

**Comment by Smoktii** [comment]
Нет отчета, нет назначений на меня ишью

**Comment by UMSF-K13-3-Sahan** [comment]
В субботу скину отчет. Пока проблемы с интернетом.

**Comment by Smoktii** [comment]
Диалог вижу, основания для засчитывания есть. Закрываю ишью.
